name: country_details
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1
  flutter_screenutil: ^5.6.0
  accordion: ^2.5.1
  sticky_headers: ^0.3.0+2
  grouped_list: ^5.1.2
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
  
  fonts:
    - family: Axiforma
      fonts:
        - asset: fonts/Axiforma-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        
  